// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	stints: () => __TAURI_INVOKE<StintRow[]>("stints"),
	laps: (file: string) => typedError<LapsView, ApiError>(__TAURI_INVOKE("laps", { file })),
	compare: (a: string, b: string) => typedError<CompareView, ApiError>(__TAURI_INVOKE("compare", { a, b })),
	report: (file: string) => typedError<string, ApiError>(__TAURI_INVOKE("report", { file })),
	session: () => __TAURI_INVOKE<SessionView>("session"),
	updateSession: (reset: boolean, car: string | null, facts: ([string, string])[]) => typedError<SessionView, ApiError>(__TAURI_INVOKE("update_session", { reset, car, facts })),
	saveTune: (values: ([string, string])[], partial: boolean) => typedError<TuneSaveView, ApiError>(__TAURI_INVOKE("save_tune", { values, partial })),
	sessions: () => __TAURI_INVOKE<SessionsView>("sessions"),
	newSession: (car: string | null, name: string | null, description: string | null) => typedError<SessionView, ApiError>(__TAURI_INVOKE("new_session", { car, name, description })),
	resumeSession: (id: string) => typedError<SessionView, ApiError>(__TAURI_INVOKE("resume_session", { id })),
	duplicateSession: (sourceId: string | null, name: string | null, description: string | null) => typedError<SessionView, ApiError>(__TAURI_INVOKE("duplicate_session", { sourceId, name, description })),
	advise: () => typedError<AdviseView, ApiError>(__TAURI_INVOKE("advise")),
	sharing: () => __TAURI_INVOKE<SharingView>("sharing"),
	setSharing: (enabled: boolean, endpoint: string | null, discard: boolean) => typedError<SharingView, ApiError>(__TAURI_INVOKE("set_sharing", { enabled, endpoint, discard })),
	sharingHistoryPlan: () => __TAURI_INVOKE<HistoryPlanView>("sharing_history_plan"),
	shareHistory: () => typedError<number, ApiError>(__TAURI_INVOKE("share_history")),
	deleteStint: (file: string, force: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("delete_stint", { file, force })),
	sessionDeletePlan: (id: string) => typedError<SessionDeletePlan, ApiError>(__TAURI_INVOKE("session_delete_plan", { id })),
	deleteSession: (id: string, deleteRuns: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("delete_session", { id, deleteRuns })),
	recordSplit: (note: string | null) => __TAURI_INVOKE<void>("record_split", { note }),
	/**
	 *  Build the stint's bundle and write it to `dest` (picked via the native
	 *  save dialog frontend-side). Returns the bundle's canonical name.
	 */
	exportStint: (file: string, dest: string) => typedError<string, ApiError>(__TAURI_INVOKE("export_stint", { file, dest })),
	effectFields: () => __TAURI_INVOKE<EffectFieldView[]>("effect_fields"),
	effectMapStatus: () => __TAURI_INVOKE<{
	samples: number,
	campaigns: number,
	/**  Unix ms of the map file's last write. */
	updatedMs: number | null,
} | null>("effect_map_status"),
	carList: () => __TAURI_INVOKE<CarView[]>("car_list"),
	pending: () => __TAURI_INVOKE<{
	/**  The netted journal note the next run will be journaled under. */
	note: string,
	changes: PendingChange[],
} | null>("pending"),
	/**
	 *  Best-guess LAN IP for the Data Out hookup screen: a connected UDP socket
	 *  reveals which local address routes outward, without sending a packet.
	 *  None when offline or loopback-only; the wizard then shows 127.0.0.1 alone.
	 */
	lanIp: () => __TAURI_INVOKE<string | null>("lan_ip"),
	/**
	 *  True when running inside a flatpak sandbox, where the tauri updater
	 *  cannot replace the app (/app is immutable; updates come via flatpak).
	 *  The frontend skips the startup update check when this is set.
	 */
	inFlatpak: () => __TAURI_INVOKE<boolean>("in_flatpak"),
};

/** Events */
export const events = {
	liveStateEvent: makeEvent<LiveStateEvent>("live-state-event"),
	qualityEvent: makeEvent<QualityEvent>("quality-event"),
	runFinishedEvent: makeEvent<RunFinishedEvent>("run-finished-event"),
	runsChangedEvent: makeEvent<RunsChangedEvent>("runs-changed-event"),
};

/* Types */
export type AbaView = {
	families: string,
	effectS: number | null,
	driftS: number | null,
	effects: { [key in string]: number | null },
};

export type AdviseView = {
	journal: string | null,
	adviceFor: string,
	steps: StepView[],
	anchor: AnchorView | null,
	aba: AbaView | null,
	landscapes: LandscapeView[],
	driftFloor: [number, number | null] | null,
	effectFloor: { [key in string]: number | null },
	inProgress: string | null,
	missing: string[],
	noLaps: string[],
	recommendations: RecommendationView[],
	currentTune: TuneFieldView[],
};

export type AnchorView = {
	vsStep: number,
	areas: string,
	changes: string,
	deltaS: number | null,
	/**  Component deltas (ideal, best, median lap); deltaS is their median. */
	currencies: [number | null, number | null, number | null],
	word: string,
	weak: boolean,
	reconciled: boolean,
	split: [number | null, number | null, number | null],
	/**  Same-setup corroboration runs pooled into a side ("runs 8-9"), if any. */
	pooled: string | null,
	effects: { [key in string]: number | null },
};

/**
 *  Command failure with enough structure for the frontend to distinguish
 *  "confirm and retry with force" (Conflict) from plain errors: the typed
 *  replacement for the HTTP status codes the dashboard used to branch on.
 */
export type ApiError = {
	kind: ErrorKind,
	message: string,
};

/**
 *  One car of the bundled ordinal->name dataset, for pickers: the user should
 *  never have to look an ordinal up themselves.
 */
export type CarView = {
	car: number,
	name: string,
};

/**  One side of an A/B comparison. */
export type CompareSide = {
	file: string,
	laps: number,
	best: number | null,
	median: number | null,
	ideal: number | null,
	standingOnly: boolean,
};

/**
 *  A/B comparison: both composited ideal-lap speed traces plus the per-bin
 *  time delta (B − A), for the overlay + segment-delta view.
 */
export type CompareView = {
	binMeters: number | null,
	a: CompareSide,
	b: CompareSide,
	speedsA: (number | null)[],
	speedsB: (number | null)[],
	timesA: (number | null)[],
	delta: (number | null)[],
	/**  The 2-of-3 vote (median of ideal/best/median-lap deltas), B minus A. */
	verdictDeltaS: number | null,
	/**  Component deltas (ideal, best, median lap). */
	currencies: [number | null, number | null, number | null],
	unequalLaps: boolean,
	carMismatch: boolean,
};

/**
 *  One entry of the effect-field registry: stable key, display label, unit
 *  hint ("" = plain number, "frac" = 0..1 shown as %), and the library noise
 *  floor. The engine owns this list (`effects::FIELDS`); the frontend must
 *  never hand-copy it.
 */
export type EffectFieldView = {
	key: string,
	label: string,
	unit: string,
	floor: number | null,
};

/**
 *  Effect-map state for the Settings screen: what the background refresher
 *  last produced. None = no map yet (nothing journaled anywhere).
 */
export type EffectMapStatus = {
	samples: number,
	campaigns: number,
	/**  Unix ms of the map file's last write. */
	updatedMs: number | null,
};

export type ErrorKind = "badRequest" | "forbidden" | "notFound" | "conflict" | "internal";

/**  Latest telemetry frame, cut down to what the Drive screen shows. */
export type FrameView = {
	raceOn: boolean,
	/**
	 *  Car ordinal from the packet (0 in menus, where everything but the timestamp
	 *  is zeroed while race is off). Lets onboarding show "car detected".
	 */
	car: number,
	carName: string | null,
	speedMps: number | null,
	rpm: number | null,
	maxRpm: number | null,
	gear: number,
	lapNumber: number,
	currentLapS: number | null,
	lastLapS: number | null,
	bestLapS: number | null,
	fuel: number | null,
	tireTempF: [(number | null), (number | null), (number | null), (number | null)],
};

/**
 *  Preview of a historic backfill: what "share existing
 *  recordings" would queue.
 */
export type HistoryPlanView = {
	campaigns: number,
	stints: number,
	mb: number | null,
	unjournaled: number,
	already: number,
};

export type LandscapeView = {
	area: string,
	phrase: string,
	key: string | null,
	/**  (value, cumulative verdict delta s, samples), ascending by value. */
	nodes: ([number | null, number | null, number])[],
	/**
	 *  Tried values whose measurements were too weak or dirty to join the
	 *  curve: (value, provisional cumulative delta). Not in the fit.
	 */
	provisional: ([number | null, number | null])[],
	/**  y = ax² + bx + c least-squares fit over the nodes (3+ nodes). */
	fit: [number | null, number | null, number | null] | null,
	vertex: number | null,
	measurements: MeasurementView[],
};

/**  Per-lap distance-binned speed traces: the lap chart's data. */
export type LapView = {
	lap: number,
	time: number | null,
	standing: boolean,
	speeds: (number | null)[],
};

export type LapsView = {
	binMeters: number | null,
	bestTime: number | null,
	/**
	 *  Every profiled lap is a point-to-point run (lap clock locked to the
	 *  race clock): the chart treats runs as comparable and drops the
	 *  standing-start label.
	 */
	pointToPoint: boolean,
	/**
	 *  Per-bin corroboration of the spliced ideal: true = a second lap
	 *  reproduces this bin's speed within splice tolerance. Drives the confidence
	 *  strip under the speed chart.
	 */
	corroborated: boolean[],
	laps: LapView[],
};

/**
 *  ~4x/s snapshot of live telemetry + recorder status (was the SSE `state`
 *  event).
 */
export type LiveStateEvent = LiveStateView;

/**  The `live-state` event payload (was the SSE `state` event). */
export type LiveStateView = {
	file: string | null,
	ageMs: number | null,
	frame: FrameView | null,
	recorder: RecorderView,
	/**
	 *  The current race start has crossed a circuit's start line (lap clock
	 *  reset seen). False = point-to-point so far, the default assumption.
	 */
	circuitSeen: boolean,
};

export type MeasurementView = {
	fromStep: number,
	toStep: number,
	desc: string,
	deltaS: number | null,
	split: [number | null, number | null, number | null] | null,
	weak: boolean,
	direct: boolean,
	effects: { [key in string]: number | null },
};

export type OutcomeView = ({ word: string; deltaS: number | null; unequalLaps: boolean }) & { error?: never } | ({ error: string }) & { deltaS?: never; unequalLaps?: never; word?: never };

/**  One slider in the pending set: differs from the last DRIVEN revision. */
export type PendingChange = {
	key: string,
	phrase: string,
	from: string | null,
	to: string,
};

/**
 *  The pending basket: tune edits saved since the last driven run, netted
 *  (the recorder's pending chain). None = the saved tune has been driven.
 */
export type PendingView = {
	/**  The netted journal note the next run will be journaled under. */
	note: string,
	changes: PendingChange[],
};

/**
 *  Data-quality summary, emitted only when it changes; None until a
 *  comparable lap exists.
 */
export type QualityEvent = QualityView | null;

/**  The `quality` event payload; None until a comparable lap exists. */
export type QualityView = {
	laps: number,
	standingOnly: boolean,
	pointToPoint: boolean,
	/**  Recordings contributing laps (> 1 = same-setup predecessors pooled in). */
	recordings: number,
	bestLapS: number | null,
	spreadPct: number | null,
	sharedKm: number | null,
	confidencePct: number | null,
	band: string,
	/**  Why confidence is not green, when it isn't (None when band is good). */
	note: string | null,
};

export type RecommendationView = {
	confidence: string,
	area: string,
	suggestion: string | null,
	/**  Machine-readable accept payload: canonical (key, value) pairs. */
	apply: ([string, string])[],
	advice: string,
	evidence: string[],
	/**  A data request (extend or tighten the map), not an optimization claim. */
	probe: boolean,
	/**
	 *  Advice tier: "fix" | "hone" | "explore" | "hold". Ranked in that
	 *  order before confidence; renderers badge non-fix tiers.
	 */
	kind: string,
};

export type RecorderView = {
	/**  "recording" | "waiting" | "external" (port busy or disabled: view-only). */
	mode: string,
	file: string | null,
	packets: number,
	/**
	 *  Milliseconds since ANY datagram hit the socket; menu packets count,
	 *  though they are never recorded. The onboarding wiring check: fresh
	 *  here + no frame = hooked up, just not driving yet. None in external
	 *  mode (another capture owns the socket) or before the first packet.
	 */
	udpAgeMs: number | null,
	/**  Car seen in raw packets (free roam counts; nothing need be recorded). */
	udpCar: number | null,
	udpCarName: string | null,
};

export type RowAnchorView = {
	vsStep: number,
	areas: string,
	deltaS: number | null,
	word: string,
	weak: boolean,
};

/**
 *  A run is over (recording closed, or the tail went stale at race-off while
 *  the recording is still open — advise reads in-progress data honestly):
 *  refresh verdicts. In external mode (another capture owns the socket)
 *  closes are only ever inferred: rotation, or the tail going stale.
 */
export type RunFinishedEvent = {
	file: string,
};

/**
 *  The newest recording rotated (covers external capture too): refresh run
 *  lists.
 */
export type RunsChangedEvent = {
	file: string | null,
};

/**
 *  What deleting an archived session would remove alongside its setup
 *  history: runs only its journal references (deletable), split from runs
 *  another journal also cites (kept) and lines whose recording is already
 *  gone.
 */
export type SessionDeletePlan = {
	runs: number,
	mb: number | null,
	shared: number,
	missing: number,
};

/**  One session in the library listing; `id: None` is the active session. */
export type SessionRow = {
	id: string | null,
	car: number | null,
	carName: string | null,
	name: string | null,
	description: string | null,
	revisions: number,
	stints: number,
};

/**
 *  The active tuning session: car, facts, latest tune revision. Baseline
 *  included so the frontend can summarize "delta vs baseline" without
 *  dumping the whole tune.
 */
export type SessionView = {
	car: number | null,
	carName: string | null,
	facts: { [key in string]: string },
	revisions: number,
	latest: { [key in string]: string } | null,
	baseline: { [key in string]: string } | null,
	campaignStart: string | null,
	/**
	 *  Baseline form seed copied from a source project at duplication;
	 *  present only until the first tune save.
	 */
	prefill: { [key in string]: string } | null,
	/**
	 *  Working tire temperature band (canonical °F) for the session's
	 *  compound, so live displays color against the same band the advice
	 *  engine uses. Legacy slick band when no compound is on file.
	 */
	tempBandF: [number | null, number | null],
};

/**
 *  The session library: the active session plus every archived sibling
 *  (<stem>-<id>.<ext>), newest first.
 */
export type SessionsView = {
	active: SessionRow,
	archived: SessionRow[],
};

/**
 *  Telemetry-collection state: consent flag, pseudonymous sender
 *  id, and outbox depth. The token itself never leaves the config file.
 */
export type SharingView = {
	enabled: boolean,
	endpoint: string,
	sender: string | null,
	queued: number,
	rejected: number,
};

export type StepFamilyView = {
	area: string,
	/**  Where this family's fingerprint is judged: "straights" | "entry" | "corners". */
	channel: string,
};

export type StepView = {
	path: string,
	laps: number,
	bestS: number | null,
	idealS: number | null,
	/**
	 *  Sample sd of flying-lap times (None under 3 laps). Report-only
	 *  consistency channel.
	 */
	scatterS: number | null,
	/**  (understeer index, front slip frac, rear slip frac). */
	balance: [number | null, number | null, number | null] | null,
	note: string | null,
	/**  Slider positions relative to baseline, when the note trail supports them. */
	pos: [number | null, number | null] | null,
	outcome: OutcomeView | null,
	/**
	 *  The vote's component deltas vs the previous step (ideal, best, median
	 *  lap); the outcome's deltaS is their median. For disagreement hedges.
	 */
	currencies: [number | null, number | null, number | null] | null,
	/**  Where the time moved vs the previous step: (entry, exit, straights). */
	split: [number | null, number | null, number | null] | null,
	anchor: RowAnchorView | null,
	/**  Families this step's note changed, each with its judged channel. */
	families: StepFamilyView[],
};

/**  One recorded stint in the sessions directory. */
export type StintRow = {
	file: string,
	bytes: number,
	car: number,
	carName: string,
};

export type TuneFieldView = {
	phrase: string,
	value: string,
	unit: string | null,
};

export type TuneSaveView = {
	ok: boolean,
	/**
	 *  The netted journal note this save will journal against the next stint;
	 *  None for the baseline (first revision) or a change that nets to zero.
	 */
	note: string | null,
	changed: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

